name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: deps
      run: sudo apt-get update && sudo apt-get build-dep kdeconnect
    - name: make
      working-directory: ..
      run: make
