name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: deps
      run: >
        echo "deb-src http://archive.ubuntu.com/ubuntu/ jammy main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list &&
        cat /etc/apt/sources.list &&
        sudo add-apt-repository universe &&
        sudo apt-get update &&
        sudo apt-get build-dep kdeconnect
    - name: make
      working-directory: ..
      run: make
